# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://ep-wispy-darkness-amh67u3t-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BRTpGYz6JK7e
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Config
spring.data.redis.host=wired-swine-79651.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAATcjAAIgcDFkNmE0NzcyZjkyYTM0MzQ5OGYwNGMyYjJkM2M5YzAwMQ
spring.data.redis.ssl.enabled=true

# App Config
spring.application.name=spring-boot-assignment
server.port=8080